name: stochastic_sim
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python version
  - python=3.11
  
  # Scientific computing libraries
  - numpy
  - scipy
  - pandas
  - sympy

  # Data visualization
  - matplotlib
  - seaborn
  - tqdm

  # Machine learning & statistics
  - scikit-learn
  - numba
  - statsmodels

  - ipykernel  # Required for Jupyter Notebooks
  - jupyterlab  # Optional, if you want Jupyter support

  # if not available in conda, install via pip
  - pip
  - pip:
      - biocircuits  # Biocircuits package for stochastic simulations
      - optuna
      - torch
      - -e .  # Install local package using pyproject.toml
