name: stochastic_sim
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python version
  - python=3.11
  
  # Scientific computing libraries
  - numpy
  - scipy
  - pandas
  - sympy

  # Data visualization
  - matplotlib
  - seaborn
  - tqdm

  # Machine learning & statistics
  - scikit-learn
  - numba

  - ipykernel  # Required for Jupyter Notebooks
  - jupyterlab  # Optional, if you want Jupyter support

  # Biocircuits package (if not available in Conda, install via pip)
  - pip
  - pip:
      - biocircuits  # Install biocircuits via pip
      - -e .  # Install local package using pyproject.toml
